// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import { CurrencyCodeRecord } from "currency-codes";
import { ApplicationStatus, CompensationType, EmploymentType, WorkArrangement } from "./enums";

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  id: number;
  email: string;
  role: 'ADMIN' | 'USER';
}>;

export type AuthResponse = {
  user: User;
};

export type Location = {
  city: string,
  state: string,
  country: string
}

export type Compensation = {
  currency: string,
  compensationType: CompensationType,
  amount: number
}

export type JobApplication = {
  userId: number,
  companyName: string,
  jobTitle: string,
  location: Location,
  employmentType: EmploymentType,
  workArrangement: WorkArrangement ,
  compensation: Compensation ,
  appliedOn: Date,
  notes: string,
  referral: boolean,
  applicationStatus: ApplicationStatus
}

export type JobApplicationsResponse = {
  data: JobApplication[]
}